services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  sandbox:
    build: ./sandbox
    volumes:
      - ./sandbox/code:/sandbox/code
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
